package ExceptionHandling;

public class Example2 {
    public static void main(String[] args) {
        try {

        }catch (Exception e){

        //}catch (ArithmeticException e){Exception 'java.lang.ArithmeticException' has already been caught

        }
    }
}
